### ISSUE TITLE
Poprawa literówki w testach

### ISSUE THREAD

**Issue by kacperwitczak** [mgdkmp13/ebiz_project#36]
@abialek677 czy ta literowka w testach jest tam celowo? prosze o naprawe

**Comment by abialek677** [comment]
> @abialek677 czy ta literowka w testach jest tam celowo? prosze o naprawe

zostawiłem bo sprawdzałem czy asserty działają 🙈

**Comment by kacperwitczak** [comment]
jakims cudem trafilo to na mastera
